### PR TITLE
Include only files in rpm spec.

### PR DESCRIPTION
**Pull request by amscanne**

### CODE REVIEW

**Comment by tjyang** [comment]
The patch actually breaking "make rpm"

[tjyang@fedora21 novm]$ make rpm
<snipped>
  /usr/lib/novm/python/novm/serial.pyc
   /usr/lib/novm/python/novm/serial.pyo
   /usr/lib/novm/python/novm/shell.pyc
   /usr/lib/novm/python/novm/shell.pyo
   /usr/lib/novm/python/novm/state.pyc
   /usr/lib/novm/python/novm/state.pyo
   /usr/lib/novm/python/novm/utils.pyc
   /usr/lib/novm/python/novm/utils.pyo
   /usr/lib/novm/python/novm/virtio.pyc
   /usr/lib/novm/python/novm/virtio.pyo
Makefile:104: recipe for target 'rpm' failed
make: **\* [rpm] Error 1
[tjyang@fedora21 novm]$ 

```
```

**Comment by amscanne** [comment]
It was working on my system, so I'm not sure what went wrong.

Anyways, I've made the list explicit with #17, so I hope the problem is gone now.

**Comment by tjyang** [comment]
Yes, the problem went away. But please make sure to include "/usr/bin/novm-docker" in the file list.

**Comment by amscanne** [comment]
Note that novm-docker should be gone as of 90a34faa8c2addf9b60ae2a0a5dd6cce5c04000b.

**Pull request merged**
